// <auto-generated />
using System.Collections.Generic;
using Biogen.DAl.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Biogen.DAl.Repository.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260218191202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Biogen.Common.Entities.DetectedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageDetectionOutcomeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("materials")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ImageDetectionOutcomeId");

                    b.ToTable("DetectedItem");
                });

            modelBuilder.Entity("Biogen.Common.Entities.ImageDetectionOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImageDetectionOutcomes");
                });

            modelBuilder.Entity("Biogen.Common.Entities.DetectedItem", b =>
                {
                    b.HasOne("Biogen.Common.Entities.ImageDetectionOutcome", null)
                        .WithMany("DetectedItems")
                        .HasForeignKey("ImageDetectionOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Biogen.Common.Entities.ImageDetectionOutcome", b =>
                {
                    b.Navigation("DetectedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
